List<Map<String, String>> allbrands = [
  {
    'id': '0',
    'name': 'Legere',
    'price': '0.3',
    'asset': 'assets/images/legere.png',
    'packprice': '5.500',
    'isPresent': 'false',
  },
  {
    'id': '9',
    'name': 'Red MarlBoro',
    'price': '0.500',
    'asset': 'assets/images/marlboro.png',
    'packprice': '10.000',
    'isPresent': 'false',
  },
  {
    'id': '1',
    'name': 'camel',
    'price': '0.500',
    'asset': 'assets/images/camel.png',
    'packprice': '10.000',
    'isPresent': 'false',
  },
  {
    'id': '2',
    'name': 'Light',
    'price': '0.500',
    'asset': 'assets/images/light.png',
    'packprice': '10.000',
    'isPresent': 'false',
  },
  {
    'id': '8',
    'name': 'Monte Carlo',
    'price': '0.400',
    'asset': 'assets/images/montecarlo.png',
    'packprice': '8.000',
    'isPresent': 'false',
  },
  {
    'id': '7',
    'name': 'Dunhil',
    'price': '0.350',
    'asset': 'assets/images/dunhill.png',
    'packprice': '6.000',
    'isPresent': 'false',
  },
  {
    'id': '4',
    'name': 'Mars',
    'price': '0.250',
    'asset': 'assets/images/mars.png',
    'packprice': '5.000',
    'isPresent': 'false',
  },
  {
    'id': '6',
    'name': 'Safir',
    'price': '0.250',
    'asset': 'assets/images/safir.png',
    'packprice': '5.000',
    'isPresent': 'false',
  },
  {
    'id': '3',
    'name': 'Karella',
    'price': '0.150',
    'asset': 'assets/images/karella.png',
    'packprice': '3.000',
    'isPresent': 'false',
  },
  {
    'id': '5',
    'name': 'Oris',
    'price': '0.150',
    'asset': 'assets/images/oris.png',
    'packprice': '3.000',
    'isPresent': 'false',
  },
];
String desc =
    'This App is user-friendly mobile application designed to assist individuals in their journey towards quitting smoking.As the developer of this app, I found quitting smoking to be a challenging journey, often accompanied by feelings of loneliness. So the purpose of this app is to provide companionship to individuals who are willing to quit or control their addiction. It achieves this by helping users track their addiction daily and keeping a record of the money spent on smoking. I hope you find what you are looking for in this app, and I look forward to the day when you successfully quit smoking and choose to delete this app.';
